spring:
  application:
    name: food-ordering-backend

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test_db
      username: harness
      password: harness
      authentication-database: test_db

server:
  port: 8080

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO